import React, { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Check, CheckCircle2, ChevronRight, Clipboard, Code2, Database, Eye, FileWarning, Github, KeyRound, LockKeyhole, Menu, Network, Server, ShieldCheck, Terminal, Users, X } from "lucide-react";
import Logo from "../components/common/Logo";

const githubUrl = "https://github.com/VarunHarinath/EnvSync";

function SectionTitle({ eyebrow, title, children, center = false }) {
  return <div className={center ? "mx-auto max-w-2xl text-center" : "max-w-2xl"}>
    <p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p>
    <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h2>
    {children && <p className="mt-4 text-base leading-7 text-muted-foreground sm:text-lg">{children}</p>}
  </div>;
}

function ProductPreview() {
  const [environment, setEnvironment] = useState("Development");
  const values = { Development: ["DATABASE_URL", "REDIS_URL", "STRIPE_TEST_KEY"], Staging: ["DATABASE_URL", "REDIS_URL", "SENTRY_DSN"], Production: ["DATABASE_URL", "REDIS_URL", "PAYMENT_PROVIDER_KEY"] };
  return <div className="overflow-hidden rounded-xl border bg-card shadow-2xl shadow-black/10">
    <div className="flex items-center justify-between border-b px-4 py-3 sm:px-5"><div className="flex items-center gap-2 text-sm font-semibold"><Logo className="h-5 w-5" /> EnvSync</div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Self-hosted</div></div>
    <div className="grid min-h-[360px] sm:grid-cols-[180px_1fr]">
      <aside className="hidden border-r bg-muted/25 p-4 sm:block"><p className="px-2 text-xs font-medium text-muted-foreground">ACME ENGINEERING</p><div className="mt-4 rounded-md bg-primary/10 px-3 py-2 text-sm font-medium text-primary">Projects</div><div className="mt-1 px-3 py-2 text-sm text-muted-foreground">Team access</div><div className="px-3 py-2 text-sm text-muted-foreground">Audit logs</div></aside>
      <div className="p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-muted-foreground">Projects / Payments API</p><h3 className="mt-1 text-xl font-semibold">Environments</h3></div><button className="rounded-md bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">+ Add secret</button></div>
        <div className="mt-6 flex gap-1 overflow-x-auto border-b">{Object.keys(values).map(name => <button key={name} onClick={() => setEnvironment(name)} className={`whitespace-nowrap border-b-2 px-3 py-2.5 text-sm ${environment === name ? "border-primary font-medium text-foreground" : "border-transparent text-muted-foreground"}`}>{name}</button>)}</div>
        <div className="mt-2 divide-y rounded-lg border">{values[environment].map((key, index) => <div key={key} className="flex items-center justify-between gap-4 px-4 py-4"><div className="min-w-0"><p className="truncate font-mono text-sm font-medium">{key}</p><p className="mt-1 font-mono text-xs tracking-widest text-muted-foreground">••••••••••••••••</p></div><div className="flex items-center gap-2 text-muted-foreground"><span className="hidden text-xs sm:inline">Updated {index + 1}d ago</span><Eye className="h-4 w-4" /></div></div>)}</div>
      </div>
    </div>
  </div>;
}

function CodeSample() {
  const [language, setLanguage] = useState("Node.js");
  const samples = { "Node.js": `const envsync = new EnvSync({\n  apiKey: process.env.ENVSYNC_API_KEY\n});\n\nconst dbUrl = await envsync.get("DATABASE_URL");`, Python: `envsync = EnvSync(\n    api_key=os.environ["ENVSYNC_API_KEY"]\n)\n\ndb_url = envsync.get("DATABASE_URL")` };
  return <div className="overflow-hidden rounded-xl border bg-[#0b0d10] text-white"><div className="flex items-center justify-between border-b border-white/10 px-4"><div className="flex">{Object.keys(samples).map(item => <button key={item} onClick={() => setLanguage(item)} className={`border-b-2 px-3 py-3 text-sm ${language === item ? "border-violet-500 text-white" : "border-transparent text-zinc-500"}`}>{item}</button>)}</div><Code2 className="h-4 w-4 text-zinc-600" /></div><pre className="overflow-x-auto p-5 text-sm leading-7 text-zinc-300"><code>{samples[language]}</code></pre></div>;
}

export default function Landing() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const steps = [[Database,"01","Store","Add environment variables once and organize them by project and environment."],[Users,"02","Control","Give teammates read or write access. Admins decide who can pull secrets."],[Code2,"03","Use","Create a scoped API key and retrieve secrets from Node.js, Python, or the REST API."]];
  const security = [[LockKeyhole,"AES-256-GCM encryption","Secrets are encrypted before they’re stored."],[Users,"Access controls","Choose who can view, change, or retrieve secrets."],[KeyRound,"Scoped API keys","Restrict application keys to a project or environment."],[Clipboard,"Audit logs","See when secrets, users, and settings were accessed or changed."],[Server,"Self-hosted","Keep EnvSync and PostgreSQL inside your infrastructure."],[ShieldCheck,"Safe sessions","Short-lived access tokens and rotated, hashed refresh tokens."]];
  return <div className="min-h-screen overflow-hidden bg-background text-foreground selection:bg-primary/25">
    <header className="sticky top-0 z-40 border-b bg-background/90 backdrop-blur"><nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#top" className="flex items-center gap-2.5 font-semibold"><Logo className="h-7 w-7" />EnvSync</a><div className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#how">How it works</a><a href="#security">Security</a><a href="#self-hosted">Self-hosted</a><a href="#setup">Setup</a></div><div className="hidden items-center gap-3 md:flex"><a href={githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 px-3 py-2 text-sm font-medium"><Github className="h-4 w-4" /> GitHub</a><Link to="/login" className="rounded-md bg-foreground px-4 py-2 text-sm font-semibold text-background">Open console</Link></div><button aria-label="Toggle navigation" onClick={() => setMobileOpen(v => !v)} className="rounded-md border p-2 md:hidden">{mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></nav>{mobileOpen && <div className="border-t px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-sm"><a href="#how">How it works</a><a href="#security">Security</a><a href="#self-hosted">Self-hosted</a><a href="#setup">Setup</a><Link to="/login" className="font-semibold text-primary">Open console →</Link></div></div>}</header>

    <main id="top">
      <section className="mx-auto max-w-7xl px-5 pb-16 pt-20 text-center sm:px-8 sm:pb-24 sm:pt-28"><div className="mx-auto max-w-4xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium text-muted-foreground"><Server className="h-3.5 w-3.5 text-primary" /> Open source and self-hosted</p><h1 className="text-5xl font-semibold tracking-[-0.045em] sm:text-7xl">Environment variables.<br/><span className="text-muted-foreground">Without the .env chaos.</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-muted-foreground sm:text-xl">Store your team’s secrets in one secure place. Control who can access them, then let your applications retrieve what they need with a simple SDK.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/login" className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground">Get started <ArrowRight className="h-4 w-4" /></Link><a href={githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-md border bg-background px-5 py-3 font-semibold"><Github className="h-4 w-4" /> View GitHub</a></div></div><div className="mx-auto mt-16 max-w-5xl text-left"><ProductPreview /></div></section>

      <section className="border-y bg-muted/25 py-20 sm:py-28"><div className="mx-auto grid max-w-6xl items-center gap-14 px-5 sm:px-8 lg:grid-cols-2"><SectionTitle eyebrow="Why EnvSync" title="Stop passing .env files around.">Secrets end up in Slack, email, old laptops, and files nobody remembers creating. EnvSync replaces that mess with one source your team can trust.</SectionTitle><div className="grid gap-3 font-mono text-sm">{[".env.production", ".env.production-final", ".env.production-new", ".env.production-actual"].map((file, i) => <div key={file} className={`flex items-center gap-3 rounded-lg border bg-background px-4 py-3 ${i === 3 ? "border-red-500/30 text-red-500" : "text-muted-foreground"}`}><FileWarning className="h-4 w-4" />{file}{i === 3 && <span className="ml-auto font-sans text-xs">Is this the latest one?</span>}</div>)}<div className="my-1 flex justify-center"><ArrowRight className="h-5 w-5 rotate-90 text-primary" /></div><div className="flex items-center gap-3 rounded-lg border border-primary/30 bg-primary/5 px-4 py-4 font-sans font-semibold"><Logo className="h-5 w-5" />One secure source in EnvSync<CheckCircle2 className="ml-auto h-5 w-5 text-emerald-500" /></div></div></div></section>

      <section id="how" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><SectionTitle eyebrow="How it works" title="Store. Control. Use." center>Three simple steps from scattered secrets to predictable access.</SectionTitle><div className="mt-14 grid gap-px overflow-hidden rounded-xl border bg-border md:grid-cols-3">{steps.map(([Icon,n,title,text]) => <article key={title} className="bg-background p-7 sm:p-9"><div className="flex items-center justify-between"><Icon className="h-6 w-6 text-primary"/><span className="font-mono text-xs text-muted-foreground">{n}</span></div><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>)}</div></section>

      <section className="border-y bg-muted/20 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-8"><SectionTitle eyebrow="Team permissions" title="Everyone gets the access they need. Nothing more.">Understand workspace and SDK access at a glance. Only administrators can grant permission to retrieve secrets with API keys.</SectionTitle><div className="mt-12 overflow-x-auto rounded-xl border bg-background"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b bg-muted/30 text-muted-foreground"><tr><th className="p-4 font-medium">Identity</th><th className="p-4 font-medium">Development</th><th className="p-4 font-medium">Staging</th><th className="p-4 font-medium">Production</th><th className="p-4 font-medium">SDK pull</th></tr></thead><tbody className="divide-y">{[["Varun","Read + write","Read + write","Read","Allowed"],["Alice","Read + write","Read","—","Not allowed"],["CI server","—","—","—","Production only"]].map(row => <tr key={row[0]}>{row.map((cell,i)=><td key={cell} className={`p-4 ${i===0 ? "font-medium" : "text-muted-foreground"}`}>{i===4 && cell!=="Not allowed" ? <span className="inline-flex items-center gap-1.5 text-emerald-600"><Check className="h-3.5 w-3.5"/>{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div></div></section>

      <section className="mx-auto grid max-w-6xl items-center gap-14 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-2"><div><SectionTitle eyebrow="Node.js + Python SDKs" title="Ask for the secret you need.">Your application sends its API key. EnvSync checks the key and its permissions before returning the secret.</SectionTitle><div className="mt-7 flex flex-wrap gap-3 text-sm text-muted-foreground"><span className="rounded-full border px-3 py-1.5">Scoped keys</span><span className="rounded-full border px-3 py-1.5">Revocable access</span><span className="rounded-full border px-3 py-1.5">Typed errors</span></div></div><CodeSample /></section>

      <section id="security" className="border-y bg-[#0a0a0b] py-20 text-white sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-8"><SectionTitle eyebrow="Security" title="Built to protect the things you don’t commit.">Security controls that are useful in day-to-day engineering, without getting in your way.</SectionTitle><div className="mt-12 grid gap-x-12 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{security.map(([Icon,title,text])=><article key={title}><Icon className="h-5 w-5 text-violet-400"/><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{text}</p></article>)}</div><a href={`${githubUrl}/blob/main/SECURITY.md`} target="_blank" rel="noreferrer" className="mt-12 inline-flex items-center gap-1 text-sm font-semibold text-violet-400">Read the security model <ChevronRight className="h-4 w-4"/></a></div></section>

      <section id="self-hosted" className="mx-auto grid max-w-6xl items-center gap-14 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-2"><SectionTitle eyebrow="Self-hosted" title="Your secrets stay with you.">Run EnvSync on your server, VM, homelab, or private network. The web app, API, and PostgreSQL database run together in Docker. No EnvSync cloud account is required.</SectionTitle><div className="rounded-xl border bg-muted/20 p-5 sm:p-8"><div className="mb-6 flex items-center gap-2 text-sm font-semibold"><Network className="h-4 w-4 text-primary"/> Your network</div><div className="grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-2 text-center text-xs sm:text-sm"><div className="rounded-lg border bg-background p-4"><Users className="mx-auto mb-2 h-5 w-5"/>Team</div><ArrowRight className="h-4 w-4 text-muted-foreground"/><div className="rounded-lg border border-primary/40 bg-primary/5 p-4"><Logo className="mx-auto mb-2 h-5 w-5"/>EnvSync</div><ArrowRight className="h-4 w-4 text-muted-foreground"/><div className="rounded-lg border bg-background p-4"><Database className="mx-auto mb-2 h-5 w-5"/>PostgreSQL</div></div><p className="mt-6 text-center text-xs text-muted-foreground">Web app + REST API + database · managed with Docker Compose</p></div></section>

      <section id="setup" className="border-y bg-muted/20 py-20 sm:py-28"><div className="mx-auto grid max-w-6xl items-center gap-14 px-5 sm:px-8 lg:grid-cols-2"><SectionTitle eyebrow="Setup" title="Clone. Run one command. You’re ready.">The guided setup starts the Docker stack, prepares PostgreSQL, configures encryption, and creates your administrator account.</SectionTitle><div className="overflow-hidden rounded-xl border bg-[#0b0d10] text-sm text-zinc-300 shadow-xl"><div className="flex items-center gap-2 border-b border-white/10 px-4 py-3 text-xs text-zinc-500"><span className="h-2.5 w-2.5 rounded-full bg-red-400"/><span className="h-2.5 w-2.5 rounded-full bg-amber-400"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-400"/><span className="ml-2">Terminal</span></div><div className="space-y-4 p-5 font-mono"><p><span className="text-zinc-600">$</span> npm run setup</p><p className="font-sans font-semibold text-white">Welcome to EnvSync</p><div className="space-y-1 text-zinc-500"><p>Organization <span className="text-white">Acme</span></p><p>Admin email <span className="text-white">admin@acme.com</span></p></div><div className="space-y-1 text-emerald-400"><p>✓ Database ready</p><p>✓ Encryption configured</p><p>✓ Administrator created</p><p>✓ EnvSync ready at http://localhost</p></div></div></div></div></section>

      <section className="mx-auto max-w-4xl px-5 py-24 text-center sm:px-8 sm:py-32"><Terminal className="mx-auto h-7 w-7 text-primary"/><h2 className="mt-6 text-4xl font-semibold tracking-tight sm:text-5xl">Replace .env chaos with one secure place.</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-muted-foreground">Open source, self-hosted, and built for the way development teams actually work.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href={githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground"><Github className="h-4 w-4"/> Get EnvSync</a><Link to="/login" className="inline-flex items-center justify-center rounded-md border px-5 py-3 font-semibold">Open console</Link></div></section>
    </main>
    <footer className="border-t"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-5 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:px-8"><div className="flex items-center gap-2 font-medium text-foreground"><Logo className="h-5 w-5"/>EnvSync</div><div className="flex gap-6"><a href={githubUrl} target="_blank" rel="noreferrer">GitHub</a><a href={`${githubUrl}#readme`} target="_blank" rel="noreferrer">Documentation</a><a href={`${githubUrl}/blob/main/SECURITY.md`} target="_blank" rel="noreferrer">Security</a></div><p>Self-hosted secrets for development teams.</p></div></footer>
  </div>;
}
