import React,{useCallback,useState} from "react";
import {Check,Code2,Eye,PenLine,Power,ShieldCheck,UserRound,UsersRound} from "lucide-react";
import {adminApi} from "../api/admin";import {useFetch} from "../hooks/useFetch";import {useToast} from "../hooks/useToast";import {cn} from "../utils";
import Button from "../components/common/Button";import Input from "../components/common/Input";import Table from "../components/common/Table";import Modal from "../components/common/Modal";

const defaultForm={fullName:"",email:"",password:"",role:"USER",access:"WRITE"};
const permissionsFor=(access,pull=false,mcpRead=false)=>({read:true,write:access==="WRITE",can_pull_secrets:pull,mcp_read:mcpRead,mcp_write:false});
const Field=({label,hint,children})=><div className="grid gap-1.5"><label className="text-sm font-medium">{label}</label>{children}{hint&&<p className="text-xs text-muted-foreground">{hint}</p>}</div>;
const Badge=({children,tone="neutral"})=><span className={cn("inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium",tone==="purple"&&"border-violet-500/20 bg-violet-500/10 text-violet-400",tone==="green"&&"border-emerald-500/20 bg-emerald-500/10 text-emerald-400",tone==="muted"&&"border-border bg-muted/40 text-muted-foreground")}>{children}</span>;
function AccessSelector({value,onChange,label}){return <div role="group" aria-label={label} className="inline-flex rounded-lg border border-border bg-muted/30 p-1"><button type="button" onClick={()=>onChange("READ")} className={cn("flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-all",value==="READ"?"bg-background text-foreground shadow-sm ring-1 ring-border":"text-muted-foreground hover:text-foreground")}><Eye className="h-3.5 w-3.5"/>View</button><button type="button" onClick={()=>onChange("WRITE")} className={cn("flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-all",value==="WRITE"?"bg-primary text-primary-foreground shadow-sm":"text-muted-foreground hover:text-foreground")}><PenLine className="h-3.5 w-3.5"/>Edit</button></div>}
function Switch({checked,onChange,label}){return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)} className={cn("relative h-6 w-11 shrink-0 rounded-full border transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50",checked?"border-primary bg-primary":"border-border bg-muted")}><span className={cn("absolute left-0.5 top-0.5 h-[18px] w-[18px] rounded-full bg-white shadow-sm transition-transform duration-200",checked?"translate-x-5":"translate-x-0")}/></button>}
function ChoiceCard({active,icon:Icon,title,description,onClick}){return <button type="button" onClick={onClick} className={cn("relative flex gap-3 rounded-lg border p-3 text-left transition-all",active?"border-primary bg-primary/5 ring-1 ring-primary/20":"border-border hover:border-muted-foreground/40 hover:bg-muted/20")}><span className={cn("mt-0.5 rounded-md p-2",active?"bg-primary/15 text-primary":"bg-muted text-muted-foreground")}><Icon className="h-4 w-4"/></span><span><span className="block text-sm font-medium">{title}</span><span className="mt-0.5 block text-xs text-muted-foreground">{description}</span></span>{active&&<Check className="absolute right-3 top-3 h-4 w-4 text-primary"/>}</button>}

export default function Users(){
  const load=useCallback(()=>adminApi.users(),[]),{data=[],refetch}=useFetch(load,[]),{toast}=useToast();
  const [open,setOpen]=useState(false),[form,setForm]=useState(defaultForm),[busy,setBusy]=useState(false),[updating,setUpdating]=useState(null);
  const create=async()=>{setBusy(true);try{await adminApi.createUser({...form,permissions:form.role==="ADMIN"?permissionsFor("WRITE",true):permissionsFor(form.access)});setOpen(false);setForm(defaultForm);await refetch();toast({title:"User created",description:`${form.email} can now sign in.`})}catch(error){toast({title:"Could not create user",description:error.message,variant:"destructive"})}finally{setBusy(false)}};
  const update=async(user,changes)=>{setUpdating(user.id);try{await adminApi.updateUser(user.id,changes);await refetch();toast({title:"Access updated",description:`Changes for ${user.email} are active immediately.`})}catch(error){toast({title:"Could not update user",description:error.message,variant:"destructive"})}finally{setUpdating(null)}};
  const columns=[
    {header:"Teammate",render:u=><div className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-gradient-to-br from-violet-500/20 to-blue-500/20 text-xs font-semibold text-violet-300">{u.full_name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}</span><div className="min-w-0"><p className="font-medium">{u.full_name}</p><p className="truncate text-xs text-muted-foreground">{u.email}</p></div></div>,className:"min-w-[220px]"},
    {header:"Role",render:u=>u.role==="ADMIN"?<Badge tone="purple"><ShieldCheck className="h-3.5 w-3.5"/>Administrator</Badge>:<Badge tone="muted"><UserRound className="h-3.5 w-3.5"/>Member</Badge>,className:"min-w-[145px]"},
    {header:"Workspace access",render:u=>u.role==="ADMIN"?<span className="text-sm text-muted-foreground">Full control</span>:<AccessSelector label={`Workspace access for ${u.email}`} value={u.permissions.write?"WRITE":"READ"} onChange={value=>update(u,{permissions:permissionsFor(value,u.permissions.can_pull_secrets,u.permissions.mcp_read)})}/>,className:"min-w-[190px]"},
    {header:"SDK access",render:u=>u.role==="ADMIN"?<Badge tone="purple"><ShieldCheck className="h-3.5 w-3.5"/>Always enabled</Badge>:<div className="flex items-center gap-3 whitespace-nowrap"><Switch label={`SDK access for ${u.email}`} checked={Boolean(u.permissions.can_pull_secrets)} onChange={checked=>update(u,{permissions:{...u.permissions,can_pull_secrets:checked}})}/><span className={cn("text-xs font-medium",u.permissions.can_pull_secrets?"text-emerald-400":"text-muted-foreground")}>{u.permissions.can_pull_secrets?"Enabled":"Blocked"}</span></div>,className:"min-w-[170px]"},
    {header:"Agent visibility",render:u=>u.role==="ADMIN"?<Badge tone="purple"><ShieldCheck className="h-3.5 w-3.5"/>Full control</Badge>:<div className="flex items-center gap-3 whitespace-nowrap"><Switch label={`Agent visibility for ${u.email}`} checked={Boolean(u.permissions.mcp_read)} onChange={checked=>update(u,{permissions:{...u.permissions,mcp_read:checked,mcp_write:false}})}/><span className={cn("text-xs font-medium",u.permissions.mcp_read?"text-emerald-400":"text-muted-foreground")}>{u.permissions.mcp_read?"Can view":"Hidden"}</span></div>,className:"min-w-[170px]"},
    {header:"Status",render:u=>u.active?<Badge tone="green"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/>Active</Badge>:<Badge tone="muted"><span className="h-1.5 w-1.5 rounded-full bg-muted-foreground"/>Inactive</Badge>},
    {header:"",render:u=><Button disabled={updating===u.id} variant="ghost" size="sm" className={cn("gap-2",u.active?"text-muted-foreground hover:text-destructive":"text-emerald-400")} onClick={()=>update(u,{active:!u.active})}><Power className="h-3.5 w-3.5"/>{u.active?"Deactivate":"Activate"}</Button>}
  ];
  return <div className="min-w-0 space-y-6"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm text-muted-foreground"><UsersRound className="h-4 w-4"/>Administration</div><h1 className="text-2xl font-bold">Team access</h1><p className="mt-1 text-muted-foreground">Manage accounts, workspace capabilities, and programmatic access.</p></div><Button onClick={()=>setOpen(true)}>Create user</Button></div><div className="min-w-0 overflow-hidden rounded-xl border bg-card shadow-sm"><Table className="rounded-none border-0 shadow-none" columns={columns} data={data||[]}/></div><Modal isOpen={open} onClose={()=>setOpen(false)} title="Create teammate" footer={<><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={!form.fullName||!form.email||form.password.length<12} isLoading={busy} onClick={create}>Create teammate</Button></>}><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name"><Input autoFocus placeholder="Jane Smith" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Field><Field label="Email address"><Input type="email" placeholder="jane@company.internal" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field></div><Field label="Temporary password" hint="At least 12 characters. Share it through a secure channel."><Input type="password" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field><Field label="Role"><div className="grid grid-cols-2 gap-3"><ChoiceCard active={form.role==="USER"} icon={UserRound} title="Member" description="Works with projects and secrets" onClick={()=>setForm({...form,role:"USER"})}/><ChoiceCard active={form.role==="ADMIN"} icon={ShieldCheck} title="Administrator" description="Full instance and user control" onClick={()=>setForm({...form,role:"ADMIN"})}/></div></Field>{form.role==="USER"&&<Field label="Workspace access" hint="SDK access stays blocked until an administrator enables it."><div className="grid grid-cols-2 gap-3"><ChoiceCard active={form.access==="READ"} icon={Eye} title="View only" description="Can browse but not change data" onClick={()=>setForm({...form,access:"READ"})}/><ChoiceCard active={form.access==="WRITE"} icon={Code2} title="Create and edit" description="Can manage projects and secrets" onClick={()=>setForm({...form,access:"WRITE"})}/></div></Field>}</div></Modal></div>;
}
