import { Router } from "express";
import { z } from "zod";
import { query,transaction } from "../db/pool.js";
import { asyncRoute,errors,ok } from "../lib/errors.js";
import { generateAgentCredential } from "../lib/security.js";
import { authenticate,requireUser } from "../middleware/auth.js";
import { requireMcpPermission,listAuthorizedEnvironments } from "../Services/agentPolicy.js";
import { listAgentSecrets,getAgentSecret,createAgentSecret,updateAgentSecret } from "../Services/secretAccess.js";
import { audit } from "../Services/audit.js";

const uuid=z.uuid(),name=z.string().trim().min(1).max(120),optionalText=z.string().trim().max(500).optional();
const parse=(schema,value)=>{const result=schema.safeParse(value);if(!result.success)throw errors.badRequest("Request validation failed",z.flattenError(result.error));return result.data};
const enrollmentAttempts=new Map();
function enrollmentLimit(req,_res,next){const key=req.ip||"local",now=Date.now(),fresh=(enrollmentAttempts.get(key)||[]).filter(x=>now-x<600000);if(fresh.length>=5)return next(errors.rateLimited());fresh.push(now);enrollmentAttempts.set(key,fresh);next()}

export const agentEnrollmentRouter=Router();
agentEnrollmentRouter.post("/enroll",enrollmentLimit,asyncRoute(async(req,res)=>{
  const input=parse(z.object({enrollmentId:uuid,clientName:name,clientVersion:z.string().max(80).optional(),transport:z.enum(["STDIO","HTTP"]).default("STDIO"),machineLabel:z.string().max(160).optional()}).strict(),req.body);
  const existing=await query("SELECT id,status FROM agents WHERE enrollment_id=$1",[input.enrollmentId]);if(existing.rowCount)throw errors.conflict("This agent enrollment already exists");
  const credential=generateAgentCredential();const agent=await transaction(async db=>{const row=(await db.query("INSERT INTO agents(enrollment_id,client_name,client_version,transport,machine_label) VALUES($1,$2,$3,$4,$5) RETURNING *",[input.enrollmentId,input.clientName,input.clientVersion||null,input.transport,input.machineLabel||null])).rows[0];await db.query("INSERT INTO agent_credentials(agent_id,credential_hash,credential_prefix) VALUES($1,$2,$3)",[row.id,credential.hash,credential.prefix]);await audit({...req,agent:row},"agent.enrolled","agent",row.id,"success",{},db);return row});
  ok(res,{agent:{id:agent.id,status:agent.status},credential:credential.raw},201);
}));

export const agentRouter=Router();agentRouter.use(authenticate);
const requireAgent=(req,_res,next)=>req.agent?next():next(errors.unauthorized("Agent credential required"));
agentRouter.get("/self",requireAgent,asyncRoute(async(req,res)=>ok(res,{id:req.agent.id,displayName:req.agent.display_name,status:req.agent.status,clientName:req.agent.client_name,machineLabel:req.agent.machine_label,expiresAt:req.agent.expires_at,environments:await listAuthorizedEnvironments(req.agent.id)})));
agentRouter.get("/environments",requireAgent,asyncRoute(async(req,res)=>ok(res,await listAuthorizedEnvironments(req.agent.id))));
agentRouter.get("/environments/:environmentId/secrets",requireAgent,asyncRoute(async(req,res)=>ok(res,await listAgentSecrets(req,parse(uuid,req.params.environmentId)))));
agentRouter.get("/environments/:environmentId/secrets/:name",requireAgent,asyncRoute(async(req,res)=>ok(res,await getAgentSecret(req,parse(uuid,req.params.environmentId),req.params.name))));
agentRouter.post("/environments/:environmentId/secrets",requireAgent,asyncRoute(async(req,res)=>{const input=parse(z.object({name:z.string(),value:z.string()}).strict(),req.body);ok(res,await createAgentSecret(req,parse(uuid,req.params.environmentId),input.name,input.value),201)}));
agentRouter.patch("/environments/:environmentId/secrets/:name",requireAgent,asyncRoute(async(req,res)=>{const input=parse(z.object({value:z.string()}).strict(),req.body);ok(res,await updateAgentSecret(req,parse(uuid,req.params.environmentId),req.params.name,input.value))}));
agentRouter.post("/access-requests",requireAgent,asyncRoute(async(req,res)=>{if(req.agent.status!=="APPROVED")throw errors.forbidden("Only approved agents can request access");const input=parse(z.object({environmentId:uuid,accessLevel:z.enum(["READ","READ_WRITE"]),durationMinutes:z.number().int().min(1).max(10080),reason:z.string().trim().min(3).max(500)}).strict(),req.body);const env=(await query("SELECT id FROM environments WHERE id=$1",[input.environmentId])).rows[0];if(!env)throw errors.notFound("Environment not found");const pending=await query("SELECT 1 FROM agent_access_requests WHERE agent_id=$1 AND environment_id=$2 AND status='PENDING'",[req.agent.id,input.environmentId]);if(pending.rowCount)throw errors.conflict("A request for this environment is already pending");const count=await query("SELECT count(*)::int count FROM agent_access_requests WHERE agent_id=$1 AND requested_at>now()-interval '1 hour'",[req.agent.id]);if(count.rows[0].count>=10)throw errors.rateLimited("Too many access requests. Try again later.");const row=(await query("INSERT INTO agent_access_requests(agent_id,environment_id,requested_access,reason,requested_duration_minutes) VALUES($1,$2,$3,$4,$5) RETURNING *",[req.agent.id,input.environmentId,input.accessLevel,input.reason,input.durationMinutes])).rows[0];await audit(req,"agent.access_requested","access_request",row.id,"success",{environment_id:input.environmentId});ok(res,row,201)}));

export const agentManagementRouter=Router();agentManagementRouter.use(authenticate,requireUser);
agentManagementRouter.get("/overview",requireMcpPermission("mcp_read"),asyncRoute(async(_req,res)=>ok(res,(await query(`SELECT count(*) FILTER(WHERE status='APPROVED')::int approved_agents,count(*) FILTER(WHERE status='PENDING')::int pending_agents,count(*) FILTER(WHERE status='REVOKED')::int revoked_agents,(SELECT count(*)::int FROM agent_environment_access WHERE revoked_at IS NULL AND expires_at>now() AND expires_at<now()+interval '24 hours') expiring_assignments,(SELECT count(*)::int FROM agent_environment_access WHERE revoked_at IS NULL AND expires_at>now()) active_temporary_access,(SELECT count(*)::int FROM agent_access_requests WHERE status='PENDING') pending_requests,(SELECT count(*)::int FROM audit_logs WHERE actor_agent_id IS NOT NULL AND result='denied' AND created_at>now()-interval '24 hours') recent_denied FROM agents`)).rows[0])));
agentManagementRouter.get("/environments",requireMcpPermission("mcp_read"),asyncRoute(async(_req,res)=>ok(res,(await query(`SELECT e.id,e.name,e.project_id,p.name project_name FROM environments e JOIN projects p ON p.id=e.project_id WHERE p.archived_at IS NULL ORDER BY p.name,e.name`)).rows)));
agentManagementRouter.get("/environments/:id/agents",requireMcpPermission("mcp_read"),asyncRoute(async(req,res)=>{const id=parse(uuid,req.params.id);ok(res,(await query(`SELECT a.id,a.display_name,a.client_name,a.status,a.last_seen_at,x.access_level,x.expires_at,x.revoked_at FROM agent_environment_access x JOIN agents a ON a.id=x.agent_id WHERE x.environment_id=$1 ORDER BY (x.revoked_at IS NULL) DESC,a.display_name,a.client_name`,[id])).rows)}));
agentManagementRouter.get("/agents",requireMcpPermission("mcp_read"),asyncRoute(async(req,res)=>{const status=req.query.status?parse(z.enum(["PENDING","APPROVED","REJECTED","REVOKED"]),req.query.status):null;ok(res,(await query(`SELECT a.*,u.email approved_by_email,(SELECT count(*)::int FROM agent_environment_access x WHERE x.agent_id=a.id AND x.revoked_at IS NULL AND (x.expires_at IS NULL OR x.expires_at>now())) assignment_count FROM agents a LEFT JOIN users u ON u.id=a.approved_by WHERE ($1::text IS NULL OR a.status=$1) ORDER BY a.created_at DESC`,[status])).rows)}));
agentManagementRouter.get("/agents/:id",requireMcpPermission("mcp_read"),asyncRoute(async(req,res)=>{const id=parse(uuid,req.params.id),agent=(await query(`SELECT a.*,u.email approved_by_email,(SELECT count(*)::int FROM agent_credentials c WHERE c.agent_id=a.id AND c.active=true AND c.revoked_at IS NULL AND (c.expires_at IS NULL OR c.expires_at>now())) active_credentials FROM agents a LEFT JOIN users u ON u.id=a.approved_by WHERE a.id=$1`,[id])).rows[0];if(!agent)throw errors.notFound("Agent not found");const assignments=(await query(`SELECT x.*,e.name environment_name,e.project_id,p.name project_name FROM agent_environment_access x JOIN environments e ON e.id=x.environment_id JOIN projects p ON p.id=e.project_id WHERE x.agent_id=$1 ORDER BY p.name,e.name`,[id])).rows;ok(res,{...agent,assignments})}));
agentManagementRouter.post("/agents/:id/approve",requireMcpPermission("mcp_write"),asyncRoute(async(req,res)=>{const id=parse(uuid,req.params.id),input=parse(z.object({displayName:name,description:optionalText,expiresAt:z.iso.datetime().nullable().optional(),assignments:z.array(z.object({environmentId:uuid,accessLevel:z.enum(["READ","READ_WRITE"]),expiresAt:z.iso.datetime().nullable().optional()}).strict()).max(100)}).strict(),req.body);const result=await transaction(async db=>{const agent=(await db.query("UPDATE agents SET display_name=$1,description=$2,status='APPROVED',approved_at=now(),approved_by=$3,rejected_at=NULL,rejected_by=NULL,revoked_at=NULL,revoked_by=NULL,expires_at=$4 WHERE id=$5 AND status IN ('PENDING','REJECTED') RETURNING *",[input.displayName,input.description||null,req.user.id,input.expiresAt||null,id])).rows[0];if(!agent)throw errors.conflict("Agent cannot be approved from its current status");for(const item of input.assignments){const env=await db.query("SELECT 1 FROM environments WHERE id=$1",[item.environmentId]);if(!env.rowCount)throw errors.badRequest("An assigned environment does not exist");await db.query(`INSERT INTO agent_environment_access(agent_id,environment_id,access_level,expires_at,granted_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(agent_id,environment_id) DO UPDATE SET access_level=excluded.access_level,expires_at=excluded.expires_at,granted_by=excluded.granted_by,starts_at=now(),revoked_at=NULL,updated_at=now()`,[id,item.environmentId,item.accessLevel,item.expiresAt||null,req.user.id])}return agent});await audit(req,"agent.approved","agent",id,"success",{assignment_count:input.assignments.length});ok(res,result)}));
agentManagementRouter.post("/agents/:id/reject",requireMcpPermission("mcp_write"),asyncRoute(async(req,res)=>{const id=parse(uuid,req.params.id),row=(await query("UPDATE agents SET status='REJECTED',rejected_at=now(),rejected_by=$1 WHERE id=$2 AND status='PENDING' RETURNING *",[req.user.id,id])).rows[0];if(!row)throw errors.conflict("Only pending agents can be rejected");await audit(req,"agent.rejected","agent",id);ok(res,row)}));
agentManagementRouter.post("/agents/:id/revoke",requireMcpPermission("mcp_write"),asyncRoute(async(req,res)=>{const id=parse(uuid,req.params.id),row=await transaction(async db=>{const agent=(await db.query("UPDATE agents SET status='REVOKED',revoked_at=now(),revoked_by=$1 WHERE id=$2 AND status<>'REVOKED' RETURNING *",[req.user.id,id])).rows[0];if(!agent)throw errors.notFound("Active agent not found");await db.query("UPDATE agent_credentials SET active=false,revoked_at=now() WHERE agent_id=$1 AND active=true",[id]);await db.query("UPDATE agent_environment_access SET revoked_at=now(),updated_at=now() WHERE agent_id=$1 AND revoked_at IS NULL",[id]);return agent});await audit(req,"agent.revoked","agent",id);ok(res,row)}));
agentManagementRouter.put("/agents/:id/assignments/:environmentId",requireMcpPermission("mcp_write"),asyncRoute(async(req,res)=>{const id=parse(uuid,req.params.id),env=parse(uuid,req.params.environmentId),input=parse(z.object({accessLevel:z.enum(["READ","READ_WRITE"]),expiresAt:z.iso.datetime().nullable().optional()}).strict(),req.body);const row=(await query(`INSERT INTO agent_environment_access(agent_id,environment_id,access_level,expires_at,granted_by) SELECT $1,$2,$3,$4,$5 WHERE EXISTS(SELECT 1 FROM agents WHERE id=$1 AND status='APPROVED') AND EXISTS(SELECT 1 FROM environments WHERE id=$2) ON CONFLICT(agent_id,environment_id) DO UPDATE SET access_level=excluded.access_level,expires_at=excluded.expires_at,granted_by=excluded.granted_by,starts_at=now(),revoked_at=NULL,updated_at=now() RETURNING *`,[id,env,input.accessLevel,input.expiresAt||null,req.user.id])).rows[0];if(!row)throw errors.badRequest("Approved agent and environment are required");await audit(req,"agent.environment_assigned","environment",env,"success",{agent_id:id,access_level:input.accessLevel,expires_at:input.expiresAt||null});ok(res,row)}));
agentManagementRouter.delete("/agents/:id/assignments/:environmentId",requireMcpPermission("mcp_write"),asyncRoute(async(req,res)=>{const id=parse(uuid,req.params.id),env=parse(uuid,req.params.environmentId);await query("UPDATE agent_environment_access SET revoked_at=now(),updated_at=now() WHERE agent_id=$1 AND environment_id=$2 AND revoked_at IS NULL",[id,env]);await audit(req,"agent.environment_revoked","environment",env,"success",{agent_id:id});ok(res,{revoked:true})}));
agentManagementRouter.get("/agent-access-requests",requireMcpPermission("mcp_read"),asyncRoute(async(_req,res)=>ok(res,(await query(`SELECT r.*,a.display_name agent_name,a.client_name,e.name environment_name,p.name project_name FROM agent_access_requests r JOIN agents a ON a.id=r.agent_id JOIN environments e ON e.id=r.environment_id JOIN projects p ON p.id=e.project_id ORDER BY r.requested_at DESC LIMIT 200`)).rows)));
agentManagementRouter.post("/agent-access-requests/:id/decision",requireMcpPermission("mcp_write"),asyncRoute(async(req,res)=>{const id=parse(uuid,req.params.id),input=parse(z.object({decision:z.enum(["APPROVED","DENIED"])}).strict(),req.body);const row=await transaction(async db=>{const request=(await db.query("SELECT * FROM agent_access_requests WHERE id=$1 AND status='PENDING' FOR UPDATE",[id])).rows[0];if(!request)throw errors.notFound("Pending access request not found");const expires=input.decision==="APPROVED"?new Date(Date.now()+request.requested_duration_minutes*60000):null;if(input.decision==="APPROVED")await db.query(`INSERT INTO agent_environment_access(agent_id,environment_id,access_level,expires_at,granted_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(agent_id,environment_id) DO UPDATE SET access_level=excluded.access_level,expires_at=excluded.expires_at,granted_by=excluded.granted_by,starts_at=now(),revoked_at=NULL,updated_at=now()`,[request.agent_id,request.environment_id,request.requested_access,expires,req.user.id]);return (await db.query("UPDATE agent_access_requests SET status=$1,reviewed_by=$2,reviewed_at=now(),expires_at=$3 WHERE id=$4 RETURNING *",[input.decision,req.user.id,expires,id])).rows[0]});await audit(req,`agent.access_request_${input.decision.toLowerCase()}`,"access_request",id,"success",{agent_id:row.agent_id,environment_id:row.environment_id});ok(res,row)}));
agentManagementRouter.get("/agent-activity",requireMcpPermission("mcp_read"),asyncRoute(async(req,res)=>{const limit=Math.min(Number(req.query.limit)||100,500);ok(res,(await query(`SELECT l.*,a.display_name agent_name,a.client_name FROM audit_logs l JOIN agents a ON a.id=l.actor_agent_id ORDER BY l.created_at DESC LIMIT $1`,[limit])).rows)}));
