import { Router } from "express";
import { z } from "zod";
import { query, transaction } from "../db/pool.js";
import { asyncRoute, errors, ok } from "../lib/errors.js";
import { decryptSecret, encryptSecret, generateApiKey, hashPassword } from "../lib/security.js";
import { authenticate, requireAdmin, requirePermission, requirePull, requireUser } from "../middleware/auth.js";
import { audit } from "../Services/audit.js";

export const resourcesRouter = Router();
resourcesRouter.use(authenticate);
const uuid = z.uuid(); const name = z.string().trim().min(1).max(100);
const validateId = (value) => { const parsed=uuid.safeParse(value); if(!parsed.success) throw errors.badRequest("Invalid resource identifier"); return parsed.data; };
const body = (schema, value) => { const parsed=schema.safeParse(value); if(!parsed.success) throw errors.badRequest("Request validation failed", z.flattenError(parsed.error)); return parsed.data; };
const ensure = (row, label) => { if(!row) throw errors.notFound(`${label} not found`); return row; };

resourcesRouter.get("/projects", requireUser, requirePermission("read"), asyncRoute(async(_req,res)=>ok(res,(await query("SELECT id,name,description,archived_at,created_at,updated_at FROM projects WHERE archived_at IS NULL ORDER BY name")).rows)));
resourcesRouter.post("/projects", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const input=body(z.object({name,description:z.string().max(500).optional()}),req.body); const row=(await query("INSERT INTO projects(name,description,created_by) VALUES($1,$2,$3) RETURNING *",[input.name,input.description||null,req.user.id])).rows[0]; await audit(req,"project.created","project",row.id); ok(res,row,201); }));
resourcesRouter.get("/projects/:id", requireUser, requirePermission("read"), asyncRoute(async(req,res)=>ok(res,ensure((await query("SELECT * FROM projects WHERE id=$1 AND archived_at IS NULL",[validateId(req.params.id)])).rows[0],"Project"))));
resourcesRouter.patch("/projects/:id", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const input=body(z.object({name}),req.body); const row=ensure((await query("UPDATE projects SET name=$1,updated_at=now() WHERE id=$2 AND archived_at IS NULL RETURNING *",[input.name,validateId(req.params.id)])).rows[0],"Project"); await audit(req,"project.updated","project",row.id); ok(res,row); }));
resourcesRouter.delete("/projects/:id", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const id=validateId(req.params.id); ensure((await query("UPDATE projects SET archived_at=now() WHERE id=$1 AND archived_at IS NULL RETURNING id",[id])).rows[0],"Project"); await audit(req,"project.archived","project",id); ok(res,{archived:true}); }));

resourcesRouter.get("/projects/:projectId/environments", requireUser, requirePermission("read"), asyncRoute(async(req,res)=>{ const id=validateId(req.params.projectId); ok(res,(await query(`SELECT e.*,count(es.id)::int secrets_count FROM environments e LEFT JOIN environment_secrets es ON es.environment_id=e.id WHERE e.project_id=$1 GROUP BY e.id ORDER BY e.name`,[id])).rows); }));
resourcesRouter.post("/projects/:projectId/environments", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const input=body(z.object({name}),req.body), projectId=validateId(req.params.projectId), slug=input.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""); const row=(await query("INSERT INTO environments(project_id,name,slug) VALUES($1,$2,$3) RETURNING *",[projectId,input.name,slug])).rows[0]; await audit(req,"environment.created","environment",row.id); ok(res,row,201); }));
resourcesRouter.patch("/environments/:id", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const input=body(z.object({name}),req.body), id=validateId(req.params.id), slug=input.name.toLowerCase().replace(/[^a-z0-9]+/g,"-"); const row=ensure((await query("UPDATE environments SET name=$1,slug=$2,updated_at=now() WHERE id=$3 RETURNING *",[input.name,slug,id])).rows[0],"Environment"); await audit(req,"environment.updated","environment",id); ok(res,row); }));
resourcesRouter.delete("/environments/:id", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const id=validateId(req.params.id); ensure((await query("DELETE FROM environments WHERE id=$1 RETURNING id",[id])).rows[0],"Environment"); await audit(req,"environment.deleted","environment",id); ok(res,{deleted:true}); }));
resourcesRouter.post("/environments/:id/clone",requireUser,requirePermission("write"),asyncRoute(async(req,res)=>{ const input=body(z.object({name}),req.body), source=validateId(req.params.id); const result=await transaction(async(db)=>{ const old=ensure((await db.query("SELECT * FROM environments WHERE id=$1",[source])).rows[0],"Environment"); const slug=input.name.toLowerCase().replace(/[^a-z0-9]+/g,"-"); const fresh=(await db.query("INSERT INTO environments(project_id,name,slug) VALUES($1,$2,$3) RETURNING *",[old.project_id,input.name,slug])).rows[0]; await db.query("INSERT INTO environment_secrets(environment_id,secret_id) SELECT $1,secret_id FROM environment_secrets WHERE environment_id=$2",[fresh.id,source]); return fresh; }); await audit(req,"environment.cloned","environment",result.id); ok(res,result,201); }));

resourcesRouter.get("/projects/:projectId/secrets", requireUser, requirePermission("read"), asyncRoute(async(req,res)=>{ const rows=(await query("SELECT id,project_id,name,created_at,updated_at FROM secrets WHERE project_id=$1 ORDER BY name",[validateId(req.params.projectId)])).rows.map((x)=>({...x,value:"••••••••"})); ok(res,rows); }));
resourcesRouter.post("/projects/:projectId/secrets", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const input=body(z.object({name:z.string().regex(/^[A-Za-z_][A-Za-z0-9_.-]{0,159}$/),value:z.string().min(1).max(65536),environmentIds:z.array(uuid).optional()}),req.body), enc=encryptSecret(input.value); const row=await transaction(async(db)=>{ const secret=(await db.query("INSERT INTO secrets(project_id,name,ciphertext,nonce,auth_tag,key_version,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7) RETURNING id,project_id,name,created_at,updated_at",[validateId(req.params.projectId),input.name,enc.ciphertext,enc.nonce,enc.authTag,enc.keyVersion,req.user.id])).rows[0]; for(const envId of input.environmentIds||[]) await db.query("INSERT INTO environment_secrets(environment_id,secret_id) SELECT $1,$2 WHERE EXISTS(SELECT 1 FROM environments WHERE id=$1 AND project_id=$3)",[envId,secret.id,secret.project_id]); return secret; }); await audit(req,"secret.created","secret",row.id); ok(res,{...row,value:"••••••••"},201); }));
resourcesRouter.patch("/secrets/:id", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const input=body(z.object({name:z.string().regex(/^[A-Za-z_][A-Za-z0-9_.-]{0,159}$/).optional(),value:z.string().min(1).max(65536).optional()}).refine(x=>x.name||x.value),req.body), id=validateId(req.params.id); const enc=input.value!==undefined?encryptSecret(input.value):null; const row=ensure((await query(`UPDATE secrets SET name=coalesce($1,name),ciphertext=coalesce($2,ciphertext),nonce=coalesce($3,nonce),auth_tag=coalesce($4,auth_tag),updated_by=$5,updated_at=now() WHERE id=$6 RETURNING id,project_id,name,created_at,updated_at`,[input.name||null,enc?.ciphertext||null,enc?.nonce||null,enc?.authTag||null,req.user.id,id])).rows[0],"Secret"); await audit(req,"secret.updated","secret",id); ok(res,{...row,value:"••••••••"}); }));
resourcesRouter.delete("/secrets/:id", requireUser, requirePermission("write"), asyncRoute(async(req,res)=>{ const id=validateId(req.params.id); ensure((await query("DELETE FROM secrets WHERE id=$1 RETURNING id",[id])).rows[0],"Secret"); await audit(req,"secret.deleted","secret",id); ok(res,{deleted:true}); }));
resourcesRouter.post("/secrets/:id/reveal", requireUser, requirePull, asyncRoute(async(req,res)=>{ const id=validateId(req.params.id), row=ensure((await query("SELECT * FROM secrets WHERE id=$1",[id])).rows[0],"Secret"); await audit(req,"secret.revealed","secret",id); ok(res,{id:row.id,name:row.name,value:decryptSecret(row)}); }));
resourcesRouter.get("/environments/:id/secrets", requireUser, requirePermission("read"), asyncRoute(async(req,res)=>{ const rows=(await query(`SELECT es.id environment_secret_id,s.id secret_id,s.name secret_name,s.created_at,s.updated_at FROM environment_secrets es JOIN secrets s ON s.id=es.secret_id WHERE es.environment_id=$1 ORDER BY s.name`,[validateId(req.params.id)])).rows.map(x=>({...x,value:"••••••••"})); ok(res,rows); }));
resourcesRouter.post("/environments/:id/secrets/:secretId",requireUser,requirePermission("write"),asyncRoute(async(req,res)=>{ const env=validateId(req.params.id),secret=validateId(req.params.secretId); const row=ensure((await query(`INSERT INTO environment_secrets(environment_id,secret_id) SELECT $1,$2 WHERE EXISTS(SELECT 1 FROM environments e JOIN secrets s ON s.project_id=e.project_id WHERE e.id=$1 AND s.id=$2) ON CONFLICT DO NOTHING RETURNING *`,[env,secret])).rows[0],"Compatible environment and secret"); await audit(req,"secret.attached","environment",env); ok(res,row,201); }));
resourcesRouter.delete("/environment-secrets/:id",requireUser,requirePermission("write"),asyncRoute(async(req,res)=>{ const id=validateId(req.params.id); ensure((await query("DELETE FROM environment_secrets WHERE id=$1 RETURNING id",[id])).rows[0],"Environment secret"); await audit(req,"secret.detached","environment_secret",id); ok(res,{deleted:true}); }));

resourcesRouter.get("/projects/:projectId/api-keys",requireUser,requirePull,asyncRoute(async(req,res)=>ok(res,(await query(`SELECT ak.id,ak.project_id,ak.environment_id,ak.name,ak.description,ak.key_prefix,ak.can_pull_secrets,ak.active,ak.expires_at,ak.last_used_at,ak.created_at,ak.revoked_at,e.name environment_name FROM api_keys ak LEFT JOIN environments e ON e.id=ak.environment_id WHERE ak.project_id=$1 ORDER BY ak.created_at DESC`,[validateId(req.params.projectId)])).rows)));
resourcesRouter.post("/projects/:projectId/api-keys",requireUser,requirePull,asyncRoute(async(req,res)=>{ if(req.user.role!=="ADMIN"&&!req.user.permissions?.write) throw errors.forbidden(); const input=body(z.object({name,description:z.string().max(500).optional(),environmentId:uuid.optional(),expiresAt:z.iso.datetime().optional(),canPullSecrets:z.boolean().optional()}),req.body); const canPull=req.user.role==="ADMIN" ? (input.canPullSecrets??true) : false, projectId=validateId(req.params.projectId); if(input.environmentId){const match=await query("SELECT 1 FROM environments WHERE id=$1 AND project_id=$2",[input.environmentId,projectId]);if(!match.rowCount)throw errors.badRequest("Environment does not belong to this project");} const generated=generateApiKey(); const row=(await query("INSERT INTO api_keys(project_id,environment_id,name,description,key_hash,key_prefix,created_by,can_pull_secrets,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,project_id,environment_id,name,key_prefix,can_pull_secrets,active,expires_at,created_at",[projectId,input.environmentId||null,input.name,input.description||null,generated.hash,generated.prefix,req.user.id,canPull,input.expiresAt||null])).rows[0]; await audit(req,"api_key.created","api_key",row.id); ok(res,{...row,key:generated.raw},201); }));
resourcesRouter.post("/api-keys/:id/revoke",requireUser,asyncRoute(async(req,res)=>{ const id=validateId(req.params.id); const row=ensure((await query("UPDATE api_keys SET active=false,revoked_at=now() WHERE id=$1 AND (created_by=$2 OR $3='ADMIN') RETURNING id",[id,req.user.id,req.user.role])).rows[0],"API key"); await audit(req,"api_key.revoked","api_key",id); ok(res,{revoked:true}); }));
resourcesRouter.patch("/api-keys/:id/permission",requireUser,requireAdmin,asyncRoute(async(req,res)=>{ const input=body(z.object({canPullSecrets:z.boolean()}),req.body),id=validateId(req.params.id); const row=ensure((await query("UPDATE api_keys SET can_pull_secrets=$1 WHERE id=$2 RETURNING id,can_pull_secrets",[input.canPullSecrets,id])).rows[0],"API key"); await audit(req,"api_key.permission_changed","api_key",id); ok(res,row); }));

resourcesRouter.get("/sdk/secrets",requirePull,asyncRoute(async(req,res)=>{ const project=req.apiKey?.project_id||validateId(req.query.projectId),env=req.apiKey?.environment_id||req.query.environmentId; const params=[project], where=["s.project_id=$1"]; if(env){params.push(validateId(env));where.push(`EXISTS(SELECT 1 FROM environment_secrets es WHERE es.secret_id=s.id AND es.environment_id=$${params.length})`);} const rows=(await query(`SELECT s.* FROM secrets s WHERE ${where.join(" AND ")} ORDER BY s.name`,params)).rows; await audit(req,"sdk.secrets_pulled","project",project); ok(res,Object.fromEntries(rows.map(row=>[row.name,decryptSecret(row)]))); }));
resourcesRouter.get("/sdk/secrets/:name",requirePull,asyncRoute(async(req,res)=>{ const project=req.apiKey?.project_id||validateId(req.query.projectId),env=req.apiKey?.environment_id||req.query.environmentId; const params=[project,req.params.name], where=["s.project_id=$1","s.name=$2"]; if(env){params.push(validateId(env));where.push(`EXISTS(SELECT 1 FROM environment_secrets es WHERE es.secret_id=s.id AND es.environment_id=$${params.length})`);} const row=ensure((await query(`SELECT s.* FROM secrets s WHERE ${where.join(" AND ")}`,params)).rows[0],"Secret"); await audit(req,"sdk.secret_pulled","secret",row.id); ok(res,{name:row.name,value:decryptSecret(row)}); }));

resourcesRouter.get("/users",requireUser,requireAdmin,asyncRoute(async(_req,res)=>ok(res,(await query("SELECT id,full_name,email,role,permissions,active,last_login_at,created_at,updated_at FROM users ORDER BY full_name")).rows)));
resourcesRouter.post("/users",requireUser,requireAdmin,asyncRoute(async(req,res)=>{ const input=body(z.object({fullName:name,email:z.email(),password:z.string().min(12).max(128),role:z.enum(["ADMIN","USER"]).default("USER"),permissions:z.object({read:z.boolean(),write:z.boolean(),can_pull_secrets:z.boolean(),mcp_read:z.boolean().optional(),mcp_write:z.boolean().optional()}).optional()}),req.body); const row=(await query("INSERT INTO users(full_name,email,password_hash,role,permissions) VALUES($1,lower($2),$3,$4,$5) RETURNING id,full_name,email,role,permissions,active,created_at",[input.fullName,input.email,await hashPassword(input.password),input.role,input.permissions||{read:true,write:true,can_pull_secrets:false,mcp_read:false,mcp_write:false}])).rows[0]; await audit(req,"user.created","user",row.id); ok(res,row,201); }));
resourcesRouter.patch("/users/:id",requireUser,requireAdmin,asyncRoute(async(req,res)=>{ const id=validateId(req.params.id), input=body(z.object({fullName:name.optional(),role:z.enum(["ADMIN","USER"]).optional(),permissions:z.object({read:z.boolean(),write:z.boolean(),can_pull_secrets:z.boolean(),mcp_read:z.boolean().optional(),mcp_write:z.boolean().optional()}).optional(),active:z.boolean().optional()}),req.body); if(id===req.user.id&&(input.role==="USER"||input.active===false)) throw errors.badRequest("You cannot demote or deactivate your own administrator account"); const row=ensure((await query("UPDATE users SET full_name=coalesce($1,full_name),role=coalesce($2,role),permissions=coalesce($3,permissions),active=coalesce($4,active),updated_at=now() WHERE id=$5 RETURNING id,full_name,email,role,permissions,active,last_login_at,created_at,updated_at",[input.fullName||null,input.role||null,input.permissions||null,input.active,id])).rows[0],"User"); await audit(req,"user.updated","user",id); ok(res,row); }));
resourcesRouter.post("/users/:id/reset-password",requireUser,requireAdmin,asyncRoute(async(req,res)=>{ const id=validateId(req.params.id), input=body(z.object({password:z.string().min(12).max(128)}),req.body); ensure((await query("UPDATE users SET password_hash=$1,password_changed_at=now() WHERE id=$2 RETURNING id",[await hashPassword(input.password),id])).rows[0],"User"); await query("UPDATE refresh_tokens SET revoked_at=now() WHERE user_id=$1",[id]); await audit(req,"user.password_reset","user",id); ok(res,{reset:true}); }));
resourcesRouter.get("/teammates",requireUser,asyncRoute(async(req,res)=>ok(res,(await query("SELECT id,full_name,email FROM users WHERE active=true AND id<>$1 ORDER BY full_name",[req.user.id])).rows)));
const shareType=z.enum(["project","environment","secret"]);
async function assertShareOwner(req,type,id){const base=type==="project"?"SELECT created_by FROM projects WHERE id=$1":type==="environment"?"SELECT p.created_by FROM environments e JOIN projects p ON p.id=e.project_id WHERE e.id=$1":"SELECT p.created_by FROM secrets s JOIN projects p ON p.id=s.project_id WHERE s.id=$1";const resource=ensure((await query(base,[id])).rows[0],type[0].toUpperCase()+type.slice(1));if(req.user.role!=="ADMIN"&&resource.created_by!==req.user.id)throw errors.forbidden("Only the resource owner or an administrator can manage sharing");}
resourcesRouter.get("/shares/:type/:id",requireUser,asyncRoute(async(req,res)=>{const type=body(shareType,req.params.type),id=validateId(req.params.id);await assertShareOwner(req,type,id);ok(res,(await query("SELECT rs.id,rs.permission,rs.created_at,u.id user_id,u.full_name,u.email FROM resource_shares rs JOIN users u ON u.id=rs.shared_with WHERE rs.resource_type=$1 AND rs.resource_id=$2 ORDER BY u.full_name",[type,id])).rows)}));
resourcesRouter.post("/shares/:type/:id",requireUser,asyncRoute(async(req,res)=>{const type=body(shareType,req.params.type),id=validateId(req.params.id),input=body(z.object({userId:uuid,permission:z.enum(["READ","WRITE"])}),req.body);await assertShareOwner(req,type,id);if(input.userId===req.user.id)throw errors.badRequest("A resource is already available to its owner");const teammate=ensure((await query("SELECT id FROM users WHERE id=$1 AND active=true",[input.userId])).rows[0],"Teammate");const row=(await query("INSERT INTO resource_shares(resource_type,resource_id,shared_with,permission,shared_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(resource_type,resource_id,shared_with) DO UPDATE SET permission=excluded.permission,shared_by=excluded.shared_by RETURNING *",[type,id,teammate.id,input.permission,req.user.id])).rows[0];await audit(req,"resource.shared",type,id);ok(res,row,201)}));
resourcesRouter.delete("/shares/:type/:id/:userId",requireUser,asyncRoute(async(req,res)=>{const type=body(shareType,req.params.type),id=validateId(req.params.id),userId=validateId(req.params.userId);await assertShareOwner(req,type,id);await query("DELETE FROM resource_shares WHERE resource_type=$1 AND resource_id=$2 AND shared_with=$3",[type,id,userId]);await audit(req,"resource.unshared",type,id);ok(res,{removed:true})}));
resourcesRouter.get("/audit-logs",requireUser,requireAdmin,asyncRoute(async(req,res)=>{ const limit=Math.min(Number(req.query.limit)||100,500); ok(res,(await query(`SELECT a.*,u.email actor_email FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT $1`,[limit])).rows); }));
resourcesRouter.get("/settings",requireUser,asyncRoute(async(_req,res)=>ok(res,(await query("SELECT * FROM instance_settings WHERE id=true")).rows[0])));
resourcesRouter.patch("/settings",requireUser,requireAdmin,asyncRoute(async(req,res)=>{ const input=body(z.object({organizationName:name.optional(),instanceName:name.optional(),publicUrl:z.url().optional(),supportEmail:z.email().nullable().optional(),timezone:z.string().max(80).optional()}),req.body); const row=(await query("UPDATE instance_settings SET organization_name=coalesce($1,organization_name),instance_name=coalesce($2,instance_name),public_url=coalesce($3,public_url),support_email=coalesce($4,support_email),timezone=coalesce($5,timezone),updated_at=now() WHERE id=true RETURNING *",[input.organizationName||null,input.instanceName||null,input.publicUrl||null,input.supportEmail||null,input.timezone||null])).rows[0]; await audit(req,"settings.updated","instance","true"); ok(res,row); }));
