export class EnvSyncError extends Error { constructor(message,{code="ENVSYNC_ERROR",status,cause}={}){super(message,{cause});this.name=this.constructor.name;this.code=code;this.status=status} }
export class AuthenticationError extends EnvSyncError{} export class PermissionError extends EnvSyncError{} export class SecretNotFoundError extends EnvSyncError{} export class NetworkError extends EnvSyncError{} export class ServerError extends EnvSyncError{}
export class EnvSync {
  #apiKey;#baseUrl;#timeout;#ttl;#cache=new Map();#fetch;
  constructor({apiKey,baseUrl,timeout=10000,cacheTtl=0,fetch:fetchImpl=globalThis.fetch}={}){if(!apiKey||!apiKey.startsWith("es_live_"))throw new TypeError("A valid EnvSync apiKey is required");if(!baseUrl)throw new TypeError("baseUrl is required");this.#apiKey=apiKey;this.#baseUrl=baseUrl.replace(/\/$/,"");this.#timeout=timeout;this.#ttl=cacheTtl;this.#fetch=fetchImpl}
  async #request(path){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.#timeout);let response;try{response=await this.#fetch(`${this.#baseUrl}/api/v1${path}`,{headers:{Authorization:`Bearer ${this.#apiKey}`,Accept:"application/json"},signal:controller.signal})}catch(cause){throw new NetworkError(cause.name==="AbortError"?"EnvSync request timed out":"Unable to reach EnvSync",{code:cause.name==="AbortError"?"TIMEOUT":"NETWORK_ERROR",cause})}finally{clearTimeout(timer)}let payload;try{payload=await response.json()}catch{throw new ServerError("EnvSync returned an invalid response",{status:response.status})}if(!response.ok){const opts={status:response.status,code:payload?.error?.code};if(response.status===401)throw new AuthenticationError(payload.error.message,opts);if(response.status===403)throw new PermissionError(payload.error.message,opts);if(response.status===404)throw new SecretNotFoundError(payload.error.message,opts);throw new ServerError(payload?.error?.message||`EnvSync returned ${response.status}`,opts)}return payload.data}
  async get(name){if(!name)throw new TypeError("Secret name is required");const cached=this.#cache.get(name);if(cached&&cached.expires>Date.now())return cached.value;const data=await this.#request(`/sdk/secrets/${encodeURIComponent(name)}`);if(this.#ttl>0)this.#cache.set(name,{value:data.value,expires:Date.now()+this.#ttl});return data.value}
  async getMany(names){if(!Array.isArray(names))throw new TypeError("names must be an array");const values=await Promise.all(names.map(async n=>[n,await this.get(n)]));return Object.fromEntries(values)}
  async getAll(){const data=await this.#request("/sdk/secrets");if(this.#ttl>0)for(const [name,value] of Object.entries(data))this.#cache.set(name,{value,expires:Date.now()+this.#ttl});return data}
  async health(){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.#timeout);try{const response=await this.#fetch(`${this.#baseUrl}/health`,{signal:controller.signal});return response.ok}finally{clearTimeout(timer)}}
  reload(name){if(name)this.#cache.delete(name);else this.#cache.clear()}
}
